# Generated by Django 5.1.1 on 2024-10-11 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 10, 11, 18, 43, 41, 840256, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
